### ISSUE TITLE
Mocha deprecation warning "--compilers" will be removed in a future version of Mocha

### ISSUE THREAD

**Issue by musichen** [EQuimper/nodejs-api-boilerplate#80]
When running mocha tests, there is a deprecation warning:

```
(node:51537) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
(node:51537) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_id' of undefined
    at Suite.<anonymous> (/Users/user/dev/nodejs-api-boilerplate/__tests__/models/user.model.test.js:111:49)
    at Generator.next (<anonymous>)
    at step (/Users/user/dev/nodejs-api-boilerplate/__tests__/models/user.model.test.js:19:191)
    at /Users/user/dev/nodejs-api-boilerplate/__tests__/models/user.model.test.js:19:437
```

https://github.com/mochajs/mocha/wiki/compilers-deprecation

**Comment by EQuimper** [comment]
@musichen thank you I'm gonna check this one :)

**Comment by EQuimper** [comment]
Should be fix now. Thank you :)

**Comment by musichen** [comment]
Thank you EQuimper :)
